pipeline:
  - type: processors.length_filter.LengthFilter
    config:
      min_length: 5
  - type: processors.snake.to_snakecase
  - type: processors.upper.to_uppercase
  - type: processors.line_counter.LineCounterProcessor